name: Build & Time
on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Configurar proyecto – generador VS 2022
      - name: Configure (CMake)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 ^
                   -DCMAKE_BUILD_TYPE=Release

      # 2) Compilar en Release
      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Build optimised
        run: cmake --build build --config Release --target flujo_opt --parallel

      # 3) Ejecutar con N = 10 para obtener métricas en el log
      - name: Run base (N=10)
        run: build\Release\flujo.exe original.txt 10

      - name: Run optimised (N=10)
        run: build\Release\flujo_opt.exe original.txt 10

      # 4) Subir el ejecutable
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: flujo.exe
          path: build\Release\flujo.exe

      - name: Upload optimised exe
        uses: actions/upload-artifact@v4
        with:
          name: flujo_opt.exe
          path: build\Release\flujo_opt.exe
